// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Persistence;

#nullable disable

namespace api.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512021748_FixUserConfiguration")]
    partial class FixUserConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("normal");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TodayMood")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserMemory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnded");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Chats", t =>
                        {
                            t.HasCheckConstraint("CK_Chats_RiskLevel", "[RiskLevel] IN ('normal', 'elevated', 'crisis')");
                        });
                });

            modelBuilder.Entity("api.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "CreatedAt");

                    b.ToTable("ChatMessages", t =>
                        {
                            t.HasCheckConstraint("CK_ChatMessages_Role", "[Role] IN ('user', 'assistant')");
                        });
                });

            modelBuilder.Entity("api.Entities.ChatScoreSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Cdt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Eng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Safe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Slp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Soc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Str")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatScoreSnapshots");
                });

            modelBuilder.Entity("api.Entities.ChatScoreTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatScoreTags");
                });

            modelBuilder.Entity("api.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicableParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicableParameters = "ANX,DEP,CDT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Record and challenge negative thoughts using cognitive behavioural therapy.",
                            Difficulty = "intermediate",
                            DurationMinutes = 15,
                            ExerciseType = "CBT",
                            Instructions = "Write the automatic thought. Rate belief (0–100%). List evidence for/against. Write a balanced thought. Re-rate belief.",
                            IsActive = true,
                            Name = "CBT Thought Record"
                        },
                        new
                        {
                            Id = 2,
                            ApplicableParameters = "ANX,STR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Calm the nervous system with a 4-4-4-4 breathing pattern.",
                            Difficulty = "beginner",
                            DurationMinutes = 5,
                            ExerciseType = "Breathing",
                            Instructions = "Inhale 4 counts → hold 4 → exhale 4 → hold 4. Repeat 4 cycles.",
                            IsActive = true,
                            Name = "Box Breathing"
                        },
                        new
                        {
                            Id = 3,
                            ApplicableParameters = "SLP,ANX",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Improve sleep quality with evidence-based pre-sleep practices.",
                            Difficulty = "beginner",
                            DurationMinutes = 10,
                            ExerciseType = "Sleep",
                            Instructions = "No screens 1 hr before bed. Cool dark room. Fixed sleep/wake time. No caffeine after noon.",
                            IsActive = true,
                            Name = "Sleep Hygiene Checklist"
                        },
                        new
                        {
                            Id = 4,
                            ApplicableParameters = "DEP,ENG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Overcome low mood through structured enjoyable activity scheduling.",
                            Difficulty = "beginner",
                            DurationMinutes = 20,
                            ExerciseType = "Behavioral",
                            Instructions = "List 5 activities you used to enjoy. Schedule one for today. Note mood before and after.",
                            IsActive = true,
                            Name = "Behavioural Activation"
                        },
                        new
                        {
                            Id = 5,
                            ApplicableParameters = "STR,ANX,SLP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduce tension by systematically tensing and releasing muscle groups.",
                            Difficulty = "beginner",
                            DurationMinutes = 15,
                            ExerciseType = "Relaxation",
                            Instructions = "Start from feet — tense each group for 5 s then release. Work up to the face.",
                            IsActive = true,
                            Name = "Progressive Muscle Relaxation"
                        },
                        new
                        {
                            Id = 6,
                            ApplicableParameters = "SOC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Combat isolation with a small, low-pressure social connection.",
                            Difficulty = "beginner",
                            DurationMinutes = 10,
                            ExerciseType = "Social",
                            Instructions = "Send one message to someone you trust. No expectation of a reply needed.",
                            IsActive = true,
                            Name = "Social Connection Task"
                        },
                        new
                        {
                            Id = 7,
                            ApplicableParameters = "SAFE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create a personal crisis plan with coping strategies and support contacts.",
                            Difficulty = "intermediate",
                            DurationMinutes = 30,
                            ExerciseType = "Safety",
                            Instructions = "List warning signs → coping strategies → trusted contacts → professional services. Review with a clinician.",
                            IsActive = true,
                            Name = "Safety Planning"
                        },
                        new
                        {
                            Id = 8,
                            ApplicableParameters = "ENG,DEP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Boost engagement by recording three good things each day.",
                            Difficulty = "beginner",
                            DurationMinutes = 5,
                            ExerciseType = "Mindfulness",
                            Instructions = "Each evening write three things that went well today and why they happened.",
                            IsActive = true,
                            Name = "Gratitude Journaling"
                        });
                });

            modelBuilder.Entity("api.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JournalText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("api.Entities.JournalScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anx")
                        .HasColumnType("int");

                    b.Property<int>("Cdt")
                        .HasColumnType("int");

                    b.Property<int>("Dep")
                        .HasColumnType("int");

                    b.Property<int>("Eng")
                        .HasColumnType("int");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<int>("Safe")
                        .HasColumnType("int");

                    b.Property<int>("Slp")
                        .HasColumnType("int");

                    b.Property<int>("Soc")
                        .HasColumnType("int");

                    b.Property<int>("Str")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId")
                        .IsUnique();

                    b.ToTable("Scores", (string)null);
                });

            modelBuilder.Entity("api.Entities.JournalTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalTags");
                });

            modelBuilder.Entity("api.Entities.MatchedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("MatchedItems");
                });

            modelBuilder.Entity("api.Entities.MatchedItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatchText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchedItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchedItemId");

                    b.ToTable("MatchedItemDetails");
                });

            modelBuilder.Entity("api.Entities.MoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("MoodEntries");
                });

            modelBuilder.Entity("api.Entities.SuggestedExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("ScoreRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("SuggestedExercises");
                });

            modelBuilder.Entity("api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Entities.UserParameterSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anx")
                        .HasColumnType("int");

                    b.Property<int>("Cdt")
                        .HasColumnType("int");

                    b.Property<int>("Dep")
                        .HasColumnType("int");

                    b.Property<int>("Eng")
                        .HasColumnType("int");

                    b.Property<int?>("LatestJournalEntryId")
                        .HasColumnType("int");

                    b.Property<int>("Safe")
                        .HasColumnType("int");

                    b.Property<int>("Slp")
                        .HasColumnType("int");

                    b.Property<int>("Soc")
                        .HasColumnType("int");

                    b.Property<int>("Str")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LatestJournalEntryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserParameterSnapshots");
                });

            modelBuilder.Entity("api.Entities.Chat", b =>
                {
                    b.HasOne("api.Entities.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Entities.ChatMessage", b =>
                {
                    b.HasOne("api.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("api.Entities.ChatScoreSnapshot", b =>
                {
                    b.HasOne("api.Entities.Chat", "Chat")
                        .WithMany("ScoreSnapshots")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("api.Entities.ChatScoreTag", b =>
                {
                    b.HasOne("api.Entities.Chat", "Chat")
                        .WithMany("Tags")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("api.Entities.JournalEntry", b =>
                {
                    b.HasOne("api.Entities.User", "User")
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Entities.JournalScore", b =>
                {
                    b.HasOne("api.Entities.JournalEntry", "JournalEntry")
                        .WithOne("Score")
                        .HasForeignKey("api.Entities.JournalScore", "JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("api.Entities.JournalTag", b =>
                {
                    b.HasOne("api.Entities.JournalEntry", "JournalEntry")
                        .WithMany("JournalTags")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("api.Entities.MatchedItem", b =>
                {
                    b.HasOne("api.Entities.JournalEntry", "JournalEntry")
                        .WithMany("MatchedItems")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("api.Entities.MatchedItemDetail", b =>
                {
                    b.HasOne("api.Entities.MatchedItem", "MatchedItem")
                        .WithMany("Details")
                        .HasForeignKey("MatchedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchedItem");
                });

            modelBuilder.Entity("api.Entities.MoodEntry", b =>
                {
                    b.HasOne("api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Entities.SuggestedExercise", b =>
                {
                    b.HasOne("api.Entities.JournalEntry", "JournalEntry")
                        .WithMany("SuggestedExercises")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("api.Entities.User", b =>
                {
                    b.OwnsMany("api.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("User_RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("api.Entities.UserParameterSnapshot", b =>
                {
                    b.HasOne("api.Entities.JournalEntry", "LatestJournalEntry")
                        .WithMany()
                        .HasForeignKey("LatestJournalEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("api.Entities.User", "User")
                        .WithOne("ParameterSnapshot")
                        .HasForeignKey("api.Entities.UserParameterSnapshot", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LatestJournalEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Entities.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ScoreSnapshots");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("api.Entities.JournalEntry", b =>
                {
                    b.Navigation("JournalTags");

                    b.Navigation("MatchedItems");

                    b.Navigation("Score");

                    b.Navigation("SuggestedExercises");
                });

            modelBuilder.Entity("api.Entities.MatchedItem", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("api.Entities.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("JournalEntries");

                    b.Navigation("ParameterSnapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
